name: Documentation

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up environment
      uses: ./.github/workflows/setup_env.yml

  build-documentation:
    runs-on: ubuntu-latest
    needs: setup-environment

    steps:
      - name: Generate Documentation
        run: |
          rm -r docs/
          pdoc --force --template-dir templates -o docs --html mimir
          mv docs/mimir/* docs/
          rm -r docs/mimir

      - name: Commit and Push Documentation
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add docs/
          git commit -m "Update documentation" -a || exit 0  # Exit if nothing to commit
          git push https://${{ secrets.MIMIR_PAT }}@github.com/${{ github.repository }}.git
