name: Tests

on: [push, pull_request]

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/setup_env.yml

  test:
    runs-on: ubuntu-latest
    needs: setup-environment
  
    steps:
      - name: Run tests
        run: |
          pytest
