name: Tests

on: [push, pull_request]

jobs:
  setup-environment:
    uses: ./.github/workflows/setup_env.yml
    with:
      python-version: '3.9'

  test:
    runs-on: ubuntu-latest
    needs: setup-environment

    steps:
      - name: Run tests
        run: pytest
